language: ruby
rvm:
- 2.3.3
branches:
  only:
  - master
before_install:
- chmod u+x deploy_init.sh
- bash deploy_init.sh
- npm install
before_script:
- gulp jsmin_travis
script:
- bundle exec jekyll build
- gulp imagemin
before_deploy:
- chmod u+x deploy.sh
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
sudo: false
env:
  global:
    secure: KK/mu6xyPZoTNbVAPX5KriTlxENq3HWUf17pZa6ECEmmRF6BxB51tPgoN7YFzkg9hzzb6mjBlhoRv/R+maZjWO+4qrBzVbFfhGvoM3/NoNHNUJX0bVgTJYDeZ210rFJLS6WAWCiBN8gI9cRdT4gV/kYBjfQU44Z1MZ6gt3B6wezOmDEY/459CH4UdEbMGqyAJZ5PaXgl+HihQDWJi8qOkjxzb5K6Lq+c2QoRGLa5WNg+UhcHTQ+PNfTlPsAy43z+S1F0XQHKOS/VPcYN8UPtewy6abNx5ppVQ6NTx6HL8YgzwQsGKvy2J/VDqLgMiquj0jlEuN0SUqEcTc1KEN7j2LY3sSTqN+Xf30d3GMU413oixUwhe++ByXLwI0I1Qpkr14ZGan6BlPtRfGSAunLzTZFKa0o/Tsakx1g+16S2EYOFdZ4cLwHXCHlHfXF7K9ulERkrGrcZunde19RoV9dttN4oFjNCuwx1lnwN28S50oKsz+KrSNA6zKLO+8uPBxrAoAHFiv3BBxH2AHLaYGCAgyr5vNieT3Fd2tumzsH+N94AW66KDMcqzYCMxT1ScecXSUDF4ecVLM5tqd5qsRrnJzOvq9KcojrsZnVBeKyAiQ6cfkPrIRfB7mKusV77cVyjC56E0JgynW1FpIozt4QmC1F5pEDDoQoH92UwWkkV3Xc=
