language: ruby
rvm:
- 2.3.3
branches:
  only:
  - master
before_install:
- chmod u+x deploy_init.sh
- bash deploy_init.sh
- npm install
before_script:
- gulp jsmin_travis
script:
- bundle exec jekyll build
- gulp imagemin
before_deploy:
- chmod u+x deploy.sh
deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
sudo: false
env:
  global:
    secure: j1f6N1EjGYwqDWCV43h53mOiMEvAH0sAN2ePVD+8Q1ajkKlA78efsz56WNZfsMjTjjfXdSGJUYAd6XfaT6zj00AbctCye7n7X7rurx7o38QkRusSUZhBWZk1zvIFjOI523AxGWfp1rGfcX3jEYJqyJ18cAvr3nQ+uisha1YuS0Gf3vp2fv3GBDw5q9kjbyJoAQIxoUx4vsDm9oDCA8jqffhilIQNEJY+datD17fiR93Q4IgUJVxjvZN0v6cRTYKdrnmzc2TcTxWAyU+Fug5ozyjdJgV98bkRiBNtI4hItmBxzQchF5mZPcd/og6/N4ijKr++ufIvRCTQs1gDDfjlh0OXmYiHCK5dTpqHGUSlLSq3fdzIrc5oC8lvDABG3Qy9sskFLIJMGXmzkVPsB5ndcHAbN+0uapQEB+/u3MFWCVS7Y64VRKcYH+jWiIdBEtlSq53sXcnQyctNTVIiYXs1i2WuXiK+TK749IXcM55xI0BSzHXBPweFy0mYNURzXaxLJMrn0aZO9P6+DWjNllt9BFeuHIzP8bIZTNL3ZdF9vkeTFP7gHqAck9Km13BQ87DkwtiEqVmCv//htivFrAPf3iVcnI3riVNd9nVul+oXBSFYorUNT6FvIOq3BcCEf9ZyGHYH59UBOc1aq04kw3YE+k38KN3yyDqu0DKofBv1VGk=
